### ISSUE TITLE
Web version

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#17]
This is a tracking issue to get notedeck working on the web

## Tasks

- [ ] https://github.com/damus-io/notedeck/issues/14
- [x] https://github.com/damus-io/notedeck/issues/15
- [x] https://github.com/damus-io/notedeck/issues/16
- [x] https://github.com/damus-io/notedeck/issues/48
