### ISSUE TITLE
Android softkeyboard support

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#199]
For input on android, we need to pop up the keyboard. This isn't directly supported by egui, since egui doesn't handle such things. egui delegates such tasks to winit, but winit does not support it yet.

External tracking issues:

- https://github.com/emilk/egui/issues/3890
- https://github.com/rust-windowing/winit/issues/1823
- https://github.com/emilk/egui/discussions/2975
- https://github.com/rust-mobile/android-activity/issues/44
- https://github.com/rust-mobile/android-activity/pull/24
- https://github.com/rust-mobile/android-activity/issues/18
- https://github.com/rust-windowing/winit/pull/2993

Progress in this area:

- https://github.com/rust-mobile/android-activity/issues/44#issuecomment-1627240142 by @lucasmerlin

@xorgy was able to make progress in winit without requiring GameActivity:

- https://github.com/rust-windowing/winit/pull/3787

Our progress:

- [x] https://github.com/damus-io/android/issues/74
- [x] https://github.com/damus-io/notedeck/issues/171
- [x] https://github.com/damus-io/notedeck/issues/187
- [x] https://github.com/damus-io/notedeck/issues/189
- [x] https://github.com/damus-io/notedeck/issues/190

**Comment by alltheseas** [comment]
@ksedgwic

**Comment by alltheseas** [comment]
Testing a comment post from Linear

**Comment by ardocrat** [comment]
From what I noticed after updating to `egui` 0.29 > 0.31.1 `GameActivity` is no longer receiving `dispatchKeyEvent` with text (only numbers) at Java code, it helped to pass events from soft keyboard to native code before. Also `GameActivity::onKeyDown` is not calling at all after focusing on input field, will wait more progress on winit integration it seems.

**Comment by jb55** [comment]
This is mostly done… just have one more keyboard issue to fix which I will open another issue for
