### ISSUE TITLE
Click note to open thread

### ISSUE THREAD

**Issue by jb55** [damus-io/notedeck#278]
I was having issues with note hitboxes so I have a dev workaround which is a circle that you click to open a note. Ideally we can get the responses fixed so that you can just click a note to open it.

Remaining:
- [x] extend hitbox to full column width [#319]
- [x] fix clicking on quoted notes [#319]
- [x] refine cached note size [#319]
- [ ] ignore redundant clicks (when already on target)
- [ ] clicking on images?
