### ISSUE TITLE
mute tracker

### ISSUE THREAD

**Issue by alltheseas** [damus-io/notedeck#570]
- [ ] https://github.com/damus-io/notedeck/issues/243
- [ ] https://github.com/damus-io/notedeck/issues/242
- [ ] https://github.com/damus-io/notedeck/issues/214
- [ ] https://github.com/damus-io/notedeck/issues/217
- [ ] https://github.com/damus-io/notedeck/issues/566

**Comment by ksedgwic** [comment]
marked #214 as done per #606
